// Per-room tile recipes. Each builder composes a room from the imported tilesets
// (see tiles.ts). Back-wall furniture sits high (base y ≈ top+40) and front
// furniture low (y ≥ ~480) so neither overlaps the door/feature billboards that
// float at y ≈ 150 (doors) and y ≈ 320–340 (features).
import Phaser from "phaser";
import { WORLD_W, type RoomDef } from "@shared";
import { buildInterior, buildOutdoor, tImg, type Item } from "./tiles";

const W = WORLD_W;

/** A table with a chair on each side. */
function table(x: number, y: number, round = true): Item[] {
  return [
    { f: "chair", x: x - 52, y },
    { f: "chair", x: x + 52, y, flip: true },
    { f: round ? "rtable" : "desk", x, y: y + 6 },
  ];
}

type Builder = (s: Phaser.Scene, def: RoomDef, top: number) => Phaser.GameObjects.GameObject[];

const RECIPES: Record<string, Builder> = {
  coffee: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_wood", wall: "wl_cream", windows: [150, 980],
      items: [
        { f: "upcab", x: 250, y: 78, depth: -1001 },
        { f: "counter", x: 250, y: top + 42 },
        { f: "fridge", x: 700, y: top + 50 },
        { f: "plant", x: 80, y: top + 86 },
        { f: "rug_round", x: 300, y: 560, depth: -999 },
        ...table(300, 500),
        ...table(720, 530),
        { f: "plant2", x: 985, y: 520 },
      ],
    }),

  pizza: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_stone", wall: "wl_cream", windows: [150, 980],
      items: [
        { f: "oven", x: 360, y: top + 44 },
        { f: "stove", x: 430, y: top + 44 },
        { f: "counter", x: 660, y: top + 42 },
        { f: "fridge2", x: 900, y: top + 50 },
        { f: "rug_red", x: 300, y: 560, depth: -999 },
        { f: "rug_red", x: 760, y: 580, depth: -999 },
        ...table(300, 500),
        ...table(760, 520),
        { f: "plant", x: 80, y: top + 90 },
      ],
    }),

  petshop: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_beige", wall: "wl_green", windows: [150, 980],
      items: [
        { f: "counter", x: 560, y: top + 42 },
        { f: "plant", x: 90, y: top + 86 },
        { f: "plant2", x: 980, y: top + 86 },
        { f: "rug_round", x: 540, y: 560, depth: -999 },
        { f: "sofa", x: 760, y: 540 },
        { f: "armchair", x: 120, y: 540 },
      ],
    }),

  dojo: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_dark", wall: "wl_grey", windows: [150, 980],
      items: [
        { f: "rug_red", x: 300, y: 540, depth: -999 },
        { f: "rug_red", x: 760, y: 540, depth: -999 },
        { f: "dlamp", x: 90, y: top + 96 },
        { f: "dlamp", x: 980, y: top + 96 },
        { f: "plant", x: 200, y: top + 70 },
        { f: "plant", x: 860, y: top + 70 },
      ],
    }),

  nightclub: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_charcoal", wall: "wl_grey", windows: [],
      items: [
        { f: "sofa", x: 150, y: 540 },
        { f: "sofa", x: 916, y: 540, flip: true },
        { f: "tv", x: 533, y: top + 40 },
        { f: "standlamp", x: 70, y: top + 120 },
        { f: "standlamp", x: 996, y: top + 120 },
        { f: "rug_round", x: 533, y: 560, depth: -999 },
      ],
    }),

  igloo: (s, def, top) =>
    buildInterior(s, top, {
      floor: "fl_wood", wall: "wl_white", windows: [150, 980],
      items: [
        { f: "fireplace", x: 533, y: top + 50 },
        { f: "rug", x: 533, y: 560, depth: -999 },
        { f: "sofa", x: 180, y: 520 },
        { f: "tv", x: 880, y: top + 46 },
        { f: "plant", x: 90, y: top + 90 },
        { f: "plant2", x: 980, y: top + 90 },
      ],
    }),
  // ---- outdoor: big scrolling snow forest. The camera follows the player; the
  // forest border + autotiled path are generated by buildOutdoor from the room's
  // size + doors. Here we add hero props scattered across the open field. ----
  town: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xe3e8ea, path: true,
      items: [
        { f: "w_snowman", x: 560, y: 720 }, { f: "w_pond", x: 1360, y: 760 },
        { f: "w_pond2", x: 1180, y: 600 }, { f: "w_log", x: 740, y: 900 },
        { f: "w_log", x: 1320, y: 920, flip: true }, { f: "w_rock", x: 540, y: 940 },
        { f: "w_bushbig", x: 700, y: 560 },
      ],
    }),

  plaza: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xe2e8ea, path: true,
      items: [
        { f: "w_pond", x: 600, y: 760 }, { f: "w_snowman", x: 1340, y: 800 },
        { f: "w_cave", x: 1420, y: 520 }, { f: "w_log", x: 760, y: 900 },
        { f: "w_rock", x: 520, y: 920 }, { f: "w_pond2", x: 1180, y: 620 },
        { f: "w_dead", x: 460, y: 560 },
      ],
    }),

  forts: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xe6edf0, path: true,
      items: [
        { f: "w_snowman", x: 600, y: 760 }, { f: "w_snowman", x: 1320, y: 820 },
        { f: "w_pond", x: 1400, y: 600 }, { f: "w_log", x: 760, y: 920 },
        { f: "w_bramble", x: 520, y: 560 }, { f: "w_rock", x: 1200, y: 940 },
        { f: "w_pond2", x: 560, y: 900 },
      ],
    }),

  ski: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xe6edf0, path: true,
      waterfalls: [{ x: 150, y: 470 }],
      items: [
        { f: "w_wall", x: 1480, y: 470 }, { f: "w_pond", x: 1280, y: 800 },
        { f: "w_snowman", x: 720, y: 820 }, { f: "w_log", x: 1100, y: 940 },
        { f: "w_rock", x: 520, y: 900 }, { f: "w_pond2", x: 600, y: 640 },
      ],
    }),

  dock: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xdfeaf7, water: { y: 360, h: 110 },
      items: [
        { f: "w_pond", x: 1340, y: 820 }, { f: "w_log", x: 760, y: 900 },
        { f: "w_snowman", x: 560, y: 840 }, { f: "w_rock", x: 1200, y: 940 },
        { f: "w_pond2", x: 1180, y: 660 }, { f: "w_dead", x: 480, y: 620 },
      ],
    }),

  beach: (s, def) =>
    buildOutdoor(s, def, {
      ground: 0xeef0d8, water: { y: 360, h: 110 },
      items: [
        { f: "w_log", x: 1200, y: 880 }, { f: "w_pond", x: 600, y: 820 },
        { f: "w_snowman", x: 1360, y: 900 }, { f: "w_rock", x: 820, y: 940 },
        { f: "w_pond2", x: 1280, y: 660 }, { f: "w_bushbig", x: 520, y: 640 },
      ],
    }),
};

const OVERLAYS: Record<string, Item[]> = {};

export function overlayProps(s: Phaser.Scene, def: RoomDef): Phaser.GameObjects.GameObject[] {
  const items = OVERLAYS[def.id];
  if (!items) return [];
  return items.map((it) => {
    const im = tImg(s, it.f, it.x, it.y, it.s, 1).setDepth(it.depth ?? it.y);
    if (it.flip) im.setFlipX(true);
    return im;
  });
}

/** Returns layout objects if the room has a tile recipe, else null (procedural fallback). */
export function buildTiledRoom(s: Phaser.Scene, def: RoomDef, top: number): Phaser.GameObjects.GameObject[] | null {
  const id = def.id.startsWith("igloo:") ? "igloo" : def.id;
  const r = RECIPES[id];
  return r ? r(s, def, top) : null;
}
